# Generated by Django 6.0.6 on 2026-06-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SnapshotAnalitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('pacientes_criticos', models.IntegerField(default=0)),
                ('pacientes_alto', models.IntegerField(default=0)),
                ('pacientes_hipertensos', models.IntegerField(default=0)),
                ('pacientes_diabeticos', models.IntegerField(default=0)),
                ('promedio_imc', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('promedio_glucosa', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
