# Generated by Django 6.0.6 on 2026-06-17 21:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_paciente_original', models.IntegerField(unique=True)),
                ('cedula', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Cédula')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='manual', max_length=20)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('registros_procesados', models.IntegerField(default=0)),
                ('registros_rechazados', models.IntegerField(default=0)),
                ('duracion_segundos', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('reporte_calidad', models.JSONField(blank=True, null=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('archivo_fuente', models.CharField(blank=True, default='', max_length=500)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogETL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(default='INFO', max_length=10)),
                ('mensaje', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('step', models.CharField(blank=True, max_length=50)),
                ('ejecucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='etl.ejecucionetl')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de consulta')),
                ('sintomas_actuales', models.TextField(blank=True, verbose_name='Síntomas actuales')),
                ('diagnostico', models.TextField(blank=True, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento indicado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('glucosa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('estado_general', models.CharField(choices=[('mejorando', 'Mejorando 📈'), ('estable', 'Estable ➡️'), ('empeorando', 'Empeorando 📉'), ('critico', 'Crítico 🚨'), ('alta_medica', 'Alta Médica ✅')], default='estable', max_length=20)),
                ('en_embarazo', models.BooleanField(default=False, verbose_name='Paciente embarazada')),
                ('semana_embarazo', models.IntegerField(blank=True, null=True, verbose_name='Semana de gestación')),
                ('condicion_especial', models.CharField(blank=True, help_text='Ej: Tratamiento poliquístico 3 meses, Quimioterapia ciclo 2...', max_length=300, verbose_name='Condición / tratamiento activo')),
                ('proxima_cita', models.DateField(blank=True, null=True, verbose_name='Próxima cita')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='etl.paciente')),
            ],
            options={
                'verbose_name': 'Consulta Médica',
                'verbose_name_plural': 'Consultas Médicas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_urgencia', models.CharField(choices=[('critica', 'Crítica'), ('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='alta', max_length=10)),
                ('tipo_alerta', models.CharField(blank=True, max_length=100)),
                ('fecha_alerta', models.DateTimeField(auto_now_add=True)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('visto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_vistas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='etl.paciente')),
            ],
            options={
                'ordering': ['-fecha_alerta'],
            },
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('altura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('clasificacion_imc', models.CharField(blank=True, max_length=20)),
                ('presion_sistolica', models.IntegerField(blank=True, null=True)),
                ('presion_diastolica', models.IntegerField(blank=True, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('glucosa', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('colesterol', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('saturacion_oxigeno', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(blank=True, max_length=20)),
                ('diagnostico_preliminar', models.TextField(blank=True)),
                ('riesgo_enfermedad', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], default='Bajo', max_length=10)),
                ('fecha_consulta', models.DateField(null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='etl.paciente')),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
